### ISSUE TITLE
Need to extract more features

### ISSUE THREAD

**Issue by OlivierBinette** [Duke-Chronicle-Project/TessTools#1]
Word confidence and font size.

**Comment by zbw8388** [comment]
~~One possible way to get font size: https://github.com/tesseract-ocr/tesseract/blob/0f7212bba7d075d357ab211c9a5617750bdb8f1a/src/ccmain/ltrresultiterator.cpp#L179~~

~~Relevant discussion: https://github.com/tesseract-ocr/tesseract/issues/1074#issuecomment-326762911~~

An easier way to do this: change the config file in `[tesseract base folder]/tessdata/configs` and set `hocr_font_info 0` to `hocr_font_info 1`. We can also create a new config file in the repo so people don't have to modify their version (preferred).
